# Generated by Django 3.1.4 on 2021-05-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriModel',
            fields=[
                ('kat_soal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode_kategori', models.CharField(max_length=20)),
                ('nama_kategori', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kategori_soal',
            },
        ),
        migrations.CreateModel(
            name='SubkategoriModel',
            fields=[
                ('sub_soal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode_sub_kategori', models.CharField(max_length=20)),
                ('nama_sub_kategori', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sub_kategori_soal',
            },
        ),
        migrations.CreateModel(
            name='SoalPilganModel',
            fields=[
                ('pilgan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_soal', models.TextField()),
                ('pilgan_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='resources')),
                ('jawaban_a', models.TextField()),
                ('jawaban_b', models.TextField()),
                ('jawaban_c', models.TextField()),
                ('jawaban_d', models.TextField()),
                ('jawaban_e', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kat_soal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kategorimodel')),
                ('sub_soal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subkategorimodel')),
            ],
            options={
                'db_table': 'soal_pilgan',
            },
        ),
        migrations.CreateModel(
            name='SoalEssayModel',
            fields=[
                ('essay_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_soal', models.TextField()),
                ('essay_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='resources')),
                ('jawaban', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kat_soal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kategorimodel')),
                ('sub_soal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subkategorimodel')),
            ],
            options={
                'db_table': 'soal_essay',
            },
        ),
    ]
